In [1]:
import pandas as pd
import glob
from collections import Counter

def clean_on_sitc(df):
    new_df = df[["DECLARANT_ISO", "PARTNER_ISO","PRODUCT_SITC", "FLOW","QUANTITY_IN_KG","VALUE_IN_EUROS"
                ,"PERIOD"]]
    new_df = new_df[new_df["PRODUCT_SITC"] >= "57000"]
    new_df = new_df[new_df["PRODUCT_SITC"] < "59000"]
    return new_df


list_of_eu_countries = ["AT","BE","BG","CY","CZ","DE","DK","EE","ES","FI","FR","GB","GR","HR","HU","IE",
        "IT","LT","LU","LV","MT","NL","PL","PT","QR","QV","QY","RO","SE","SI","SK"]

In [2]:
final_output = pd.DataFrame(columns=["Period", "Export_Value_in_Euros", "Export_Quantity_in_KG", 
           "Import_Value_in_Euros", "Import_Quantity_in_KG"])

In [3]:
dir_path = "/home/cratus/Project/Data"
file_path = "/home/cratus/Project/Data/full202002.dat"
all_data = glob.glob(dir_path + "/*.dat")

In [4]:
for file in all_data:
    df = pd.read_csv(file, index_col=None, header=0)
    df1 = clean_on_sitc(df)
    for country in list_of_eu_countries:
        df1.drop(df1[df1['PARTNER_ISO'] == country].index, inplace = True)
    
    period = df["PERIOD"].iloc[2]
    
    monthly_import = df1.copy()
    monthly_import.drop(monthly_import[monthly_import["FLOW"] == 2].index, inplace = True)
    
    monthly_import_quantity = monthly_import["QUANTITY_IN_KG"].sum()
    monthly_import_value = monthly_import["VALUE_IN_EUROS"].sum()
    
    monthly_export = df1.copy()
    monthly_export.drop(monthly_export[monthly_export["FLOW"] == 1].index, inplace = True)
    
    monthly_export_quantity = monthly_export["QUANTITY_IN_KG"].sum()
    monthly_export_value = monthly_export["VALUE_IN_EUROS"].sum()
    
    final_output.loc[len(final_output.index)] = [period, monthly_export_value, monthly_export_quantity
                                                 , monthly_import_value, monthly_import_quantity]
    print(f"Finished {period}")

Finished 201905
Finished 201911
Finished 201901
Finished 201812
Finished 202108
Finished 202011
Finished 201702
Finished 201910
Finished 202002
Finished 202010
Finished 201701
Finished 201804
Finished 201704
Finished 201709
Finished 201810
Finished 202006
Finished 201805
Finished 201711
Finished 201707
Finished 201904
Finished 202007
Finished 202003
Finished 202105
Finished 201912
Finished 202101
Finished 201708
Finished 201909
Finished 202103
Finished 201803
Finished 202001
Finished 202107
Finished 201801
Finished 201710
Finished 201808
Finished 202009
Finished 201712
Finished 201906
Finished 202102
Finished 201902
Finished 201806
Finished 201705
Finished 202004
Finished 201903
Finished 201703
Finished 202012
Finished 201706
Finished 201807
Finished 201809
Finished 201907
Finished 202008
Finished 202104
Finished 201802
Finished 201908
Finished 201811
Finished 202005
Finished 202106

In [5]:
final_output.sort_values(by = "Period")

,Period,Export_Value_in_Euros,Export_Quantity_in_KG,Import_Value_in_Euros,Import_Quantity_in_KG
10,201701,3301886443,1666374047,2043406815,989951540
6,201702,3307861691,1606363086,1901881872,945729192
43,201703,3838610602,1751097985,2308822842,1115714174
12,201704,3259997722,1420991842,2080045989,1009163563
40,201705,3765374544,1643213898,2378692769,1103174092
45,201706,3630500328,1615792859,2192496831,1060329097
18,201707,3460939605,1500938246,2214294418,1118137719
25,201708,3429528474,1578987354,2159429585,1080485689
13,201709,3381055377,1503164034,2238226970,1181731082
32,201710,3514903794,1529180635,2258745979,1190780660
17,201711,3537325630,1567320796,2106294158,1082917699
35,201712,3185899108,1455110886,1780276322,930526618
31,201801,3544495826,1644231792,2290773616,1131592162
51,201802,3399803217,1553224244,2080400063,1059804083
28,201803,3707271114,1642179781,2268720153,1149572710
11,201804,3533596987,1572843569,2410164822,1215720768
16,201805,3667647637,1634176058,2484097721,1262287403
39,201806,3707841627,1598597918,2414226570,1155897049
46,201807,3621314965,1549974277,2442126225,1184335182
33,201808,3511774307,1479476857,2259726132,1079624702
47,201809,3375192192,1394779091,2249185842,1088748861
14,201810,3713684772,1560848148,2523670030,1239927647
53,201811,3481711831,1453936194,2316094965,1127122172
3,201812,2956501468,1260967587,1883401914,944025569
2,201901,3459929030,1514838104,2578630236,1260019746
38,201902,3289730994,1423856169,2378887849,1222953032
42,201903,3529237949,1512946875,2489335304,1261858683
19,201904,3484152999,1493151251,2698086269,1384244079
0,201905,3712991900,1566640868,2676308909,1365436374
36,201906,3328226721,1395804708,2290873321,1159903596
48,201907,3696415655,1591630472,2548388948,1307209759
52,201908,3336818888,1478420992,2187398200,1119710960
26,201909,3396116185,1462405847,2272690727,1189148633
7,201910,3708998480,1642073362,2391590134,1205425746
1,201911,3311583647,1465291979,2126185099,1093593186
23,201912,3133059107,1413264884,1787000801,938775386
29,202001,3524000089,1617783317,2324724683,1174699055
8,202002,3346103610,1457922594,1933218642,1060432044
21,202003,3574340491,1570776093,2217241371,1175771495
41,202004,3201971108,1420662719,2157978784,1130024631
54,202005,2760007003,1319477348,1917929281,1064368072
15,202006,2990283266,1524134656,1992392468,1179945022
20,202007,3205410692,1646335459,1913702340,1119251834
49,202008,2724869436,1369099386,1623952475,982799207
34,202009,3187854766,1590153693,1789336431,1035500070
9,202010,3354769532,1642931179,1808374350,1034954572
5,202011,3271001806,1590670286,1797360831,999734634
44,202012,3306157201,1646767514,1614094492,890490029
24,202101,3385108933,1497759858,1881530384,969018773
37,202102,3473985350,1550940784,1945179592,989368958
27,202103,4160419636,1729154440,2441604842,1175525365
50,202104,3825798187,1505880743,2646212480,1234087102
22,202105,3723086882,1391296276,2753038030,1264789699
55,202106,3991959853,1464845194,3065936888,1382956259
30,202107,3919757901,1419660991,3020104372,1368487618
4,202108,3702246400,1356127366,2975277980,1313760549

In [6]:
save_path = "/home/cratus/Project/Data/output.xlsx"

In [7]:
final_output.to_excel(save_path)